import { Header } from '@/components/layout/header/header'
import { routing } from '@/i18n/routing.ts'
import Provider from '@/provides/Provider'
import type { Metadata } from 'next'
import { hasLocale } from 'next-intl'
import { setRequestLocale } from 'next-intl/server'
import { Geist, Geist_Mono } from 'next/font/google'
import { notFound } from 'next/navigation'
import './globals.css'

export function generateStaticParams() {
	return routing.locales.map(locale => ({ locale }))
}

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

type Props = {
	children: React.ReactNode
	params: Promise<{ locale: string }>
}

export default async function RootLayout({ children, params }: Props) {
	const { locale } = await params
	if (!hasLocale(routing.locales, locale)) {
		notFound()
	}

	setRequestLocale(locale)

	return (
		<html
			lang={locale}
			suppressHydrationWarning
		>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased w-full min-h-screen`}
			>
				<Provider locale={locale}>
					<div className='mx-auto container max-sm:pt-6 max-sm:pb-20 max-sm:px-4'>
						<Header />
						{children}
					</div>
				</Provider>
			</body>
		</html>
	)
}
